dist: trusty
stages:
- lint
- test
- deploy
language: node_js
node_js: '10'
cache:
  directories:
  - "~/.npm"
  - node_modules
notifications:
  email: false
git:
  submodules: false
before_install:
- "git config --global user.name \"\U0001F916\""
jobs:
  include:
  - stage: lint
    script: yarn lint
    skip_cleanup: true
  - stage: deploy
    if: branch = master
    before_deploy:
    - yarn build
    deploy:
      provider: script
      script:
      - yarn travis-deploy-once "yarn semantic-release"
      skip_cleanup: true
env:
  global:
  - secure: fud0Nu8JW/Ke63xN8rA/C5RI40mJCTDoKfTaxSao8bVzVNqzauO0bDUxVTiJOqxfOaRP46K3jTETob0i2J/HcNF/vREqM5ZZbYIVrx45erW2ZzoXZiD0LqYtF5/IHpIVYI3WjKUXx6x/Q/sJ3TvVASKogmP1ogH/4LxqptLhaalU8xDm++FPw8uXeEgqBIOkgtTAlKvQqRiZ/iVQ1yxNpD5Quedh7VNaME79nig+e28y0H3vCiLUPXH+kV+BOJZVT8rIKjxiY9vrxMu+KJ8P969rFYq9H2i6juZ90b38Zy3E1Yx7MvTT18WxjUKk4MLXu+WpqZK/f/rgjV7LxYdD9cbVJ223ALcYVQbrpVFqGnls98Vnwtq0YFIV8EdBjQXPXjuzQiy0GC3UO71hqOke6lEGTB9qkuX3i1dGUVaNG3cyLC7lX0pyNlH0eXBrDxF2PWhnq0n6FCCPqewLAF7L0cRRwYH5PCpzd3TvFuT0iDNZQrp7hdqcu5pkrguDEz7kAKOL9lShqQpnQGhNM5mAxgYmKNcFONfy0w96WolLwxALbPSMts+88PZqZm1FRWdiSvKo0bwt0nY3GWd8yQk2JLU1vZ5gceaTGrgydYLMLXsjEa00XNLLzqY2H0eHJyLu+xaSFcKis+SpzG9rIcaUPaqzZvIO5ltuHZ6KYAHhsTQ=
  - secure: ebEkGPYMYgcL8x52f+1LwCafNQd64BLlyVOXqN0bpGh1dL++Vjxy/Ntf0x1xbBeIu3bFghwNT2grqfhS46eOvAGUZE+ebXdKsNFG1hiur+njXQgJIrKJOrQY0C/IByT3HQjo8s+31VXBD1n0GyVatOSm0KtJEkm+7HOVPvfd3A/EKSYBdJbun/gPzmUdxgoizrIqbhQo5FHLzS1h6X+LJuUSXn6THrnkw6LmvwGIPqSz6A86Kt95XjecqWDWtjyuh9YmN/YHU/xb9gNls07+bKmWvapDlS6rE3cf16llUz0CaTARpRzsN+rUvFMx0CVce2TY7i/7V5If/CDYHxnTqZD+/rcmtYeFtO/LzhyePG7iYG+2n6UOzu2gBcDivMXqIQ16vHlvYmqt3XOmYXl0CYl5PZPKagaN2nwfovwUBkBuRMUNi/268dlLU7Jj9jlbhA2b4kL/WOJlRStyJ5hgxMzrtfJvVBYhJP6CK5J34Cyq8HDtFWXOGwKvBy6Kwj+cRPk2X7+gO5HoVKC93eJ3HLTSkB9QSAatDM+7oLG+5UkVRJGteNzLQguwyz+kNJHjTyL5lvJ0dzTSvR26cwQVWnPs0zmv+dPxDc98+RuBfbf56al26bZuTZIpdYhhqfZ3kq1aKane1KMaFYuFXsGR09nmn8ehKRKfS4Kuc5pMnH8=
