dist: trusty
stages:
- lint
- test
- deploy
language: node_js
node_js: '10'
cache:
  directories:
  - "~/.npm"
  - node_modules
notifications:
  email: false
git:
  submodules: false
before_install:
- "git config --global user.name \"\U0001F916\""
jobs:
  include:
  - stage: lint
    script: yarn lint
    skip_cleanup: true
  - stage: deploy
    if: branch = master
    before_deploy:
    - yarn build
    deploy:
      provider: script
      script:
      - yarn travis-deploy-once "yarn semantic-release"
      skip_cleanup: true
env:
  global:
  - secure: JQNHUoNeC0ee4TiRTUR3pFBv8qPlX4SF2nFBVpaAv0Ken93bZ3liFTFpevVC8oWx0tVeALlmA47Xin2Ys98rnxr0P+QLhJmf0tjh/hsoNKA8JUi/bm6Mb8Rb25u4O6pj+FXegXec7vInwSR0el4cGpXCR/h55+H+qt2qP60t6SzgMBgcOSQrXctFz3IxlMLpv+ZoVREFhMYlwfur5s335p5QvqHTzuH6TViQKHjZOULknziGTN5e47CcuhPUI3kQVxzT6ADs64Bh4AIegV3ojRNxBpoW1g2HgpWn2XlA96I+kYAWQyzCrOTheMAh0m6zMGKjqbruTVqDe1GQctIG0DVzPkOexoS8ICV1t2OVoV7Xmod8PYurPvaiM81ztmqo6xD2xrO0GyEu4kLeoasOL54ljioC2KQ98txjBtHzVSTsX+fs0pXI8dk7/edgRhHVL+5xauxbXMqvlIWc9ep1VEUCbbxbhoAVP53SLk2J2rugwXcsPCP9HwwNUmPxinoMPduJwUk3RmVBCLzuSdCxRx2aX/aqSudlhsCT7q2aDgf9drSdzYxJiB2OSXcdB3yRbWwgdL6yrvWA7Dy8l3jrKCBJwSldIQ6ErAMqszMTDgZcUvGqFuv0PVnQ7oCdv/UQh+9WfRannQSkXh7nb6DikVctIsqSoLQrbL1Ebs6ix3Y=
  - secure: nF1pwyWfK5/ojRQnwucEM8UhJg7QpTLdGVe04gJlSvzjSuh4xp/zPsVAww3re4XnfouKEPZbEZwXqlvrJol4JH7WleFWHjRHk9tr2FUhs5RfShHvIwX719JiWl7HYVTDvIlTYcM8IiE0h5wtm3oiOYJgxEgdNFvCX/W5ZKoDwRXTt3MKc3xBr7AiYKKNPUp10CuI8KFsv8krYoOLye/tJwlV2nIddJi5qwNmwdtlWm19JI3iYpApk21xvPVKDFdRrdYXr/lUg9a420XuOmzZT1jAwfIAQBAzHvvRJ5qD5er8qLSGyKt/zjlYIH8i2Z0nxk2tGjdxlXvLAUiuLGFlAAtHzN1Ykp3J7n3cUjwJPh0dL+Sx/sOo5Fj3uyPSvAuHVNIFeTET2JBBA92aU1irmwG2YyBJyVx5qUV9AkL/SPF7KLs6fw93o/tUolpKKjCj7JC8Ad3Cq0O4Y5iI7xO00pG+sXaBQWT9VW0dKuVewLE6UyZesiGjR7uMGyPGaZHoqonnOQndqZN4MTK/L36j+LkAACzYS2QSacreqXWGKusZ1yFz++p45lZ36cDF29bjz2XfFRGBlq5QFyKWUZB8Vf6CEQvZeQ3jH9OYEcOhbieTQvP7nAcGITUTe43x2fr1O6DcQMYv1tgBahSTblcNRAEDCKKrH+ZgvL5oPe2U2No=
