dist: trusty
stages:
- lint
- test
- deploy
language: node_js
node_js: '10'
cache:
  directories:
  - "~/.npm"
  - node_modules
notifications:
  email: false
git:
  submodules: false
before_install:
- "git config --global user.name \"\U0001F916\""
jobs:
  include:
  - stage: lint
    script: yarn lint
    skip_cleanup: true
  - stage: deploy
    if: branch = master
    before_deploy:
    - yarn build
    deploy:
      provider: script
      script:
      - yarn travis-deploy-once "yarn semantic-release"
      skip_cleanup: true
env:
  global:
  - secure: Cu17rcrspn2I9AJrjriZVfprnts6D+zKgz+t8uukHNi04/2BPVkcCPQt/2BRuK4JpBZDvtsKRFIrdj92irjaz9vL1xLmuKJeMrUbsYbg6yQemljywaCSD5LVljuHiG+swjTxjvZeKtKcK5qxzMrKzGq7W6EGENlKEXxCxNwaJ7h49WfiCYB1PE0vHvSfwlGo+q/8YO1NMcVF4j7x3JsWyFuYz1rHo+vsa1whxv+TZ3n1ZbzFu5QSWfOGLNHplCPcI/Tyc97pEZOxxf114Dyp2x1kryUYTDSIZMiA+Et24xCRLtK5uiOsXBWjMr7ej3GUklSZ8bCbttQbcxxmbApUeT8b7kphnvI7c7oBrMYKXXMS3qS1IbFd/34EeOb/EvVar1pPXj1NUz0bXK+e84T/LnJD/664wz9dKZowoJNWAF8RicnQydpxW6b64uFi4rGFkj5GVmPbwzL51snGSt5RD9GOFN0JnfXudT0p3NxoKxIgz3V8me+Zem/7ZmS98UVD/R2/Cw1HQOoBV7db4NVbcQtJEhnDqK5tNJNYMyFsw9Ih+DbuBYfYMKlH8WQUChJwQDQo+7/wxmq3/73KVLaLbJF1bOQ6OvwRV+mCBhxvjxqJe95LA5mtcrDdPRC/1a0024/XxYhCVPiW/3IVVvMMvxNYDmsiJAXtPHe9feABF0Y=
  - secure: V7dCigWnQxOr2AZNnfHG1xn2z5gQzDr3PS+kaJtUI0XrFumRV30/69BVCJg3wLFzurijNSLCXsxy1+19zQ1AvYdWQdpYtKaMtTa9KePOzY1B8AeFnOWBW1JJ/gudWLB2P9fTuIGW/RzlHgb3ROpbs1xbZjNVojU2C81/gO/BrkK/fZPZa/lyT/yBU55PBDxw8s6jbxUU41jLrT2PqMvQ74/bA6AtqtJUtoY8AZyosABvfYbMQXy/CWKCyd+ih9A+xTRgwtbE/GYdYpVmvA30q8Q4LBL5bMW9DWXTJ9EOju2+p6UtcheOGtVyAwHhvGX5j8BPuW2mJVc5JCJ65CZLoM1TDpmEPogPiJsBpQoCpgW//cOY2w7aYQTw9Ap2VRVZT8GVjF8icu3S165C9stajlaH+IfNBZx2+No0w0DoatJpJRJWQnzembYIyFyzh01eqQALkPcZGpgeXNvvDt96Y6zDudR8ivbIjFAGiABQnMi29JAPBnbdTusoQogc3zhKehmKoIY53P2/3vU6VUykh6eBSurcm6gap1qvZgBCQZa+9r50Yq61QoD/ft0CaYEuz9NC0SNz/0wEyJYRCLE2GPOhTNeKbQe6ASEFz8WiPGMpVYRQttfcKUWjta8AGp3bEWYpovfymBdKw8QYMYXaf/uNc45hoMBS9spcSEp8Geg=
